### PR TITLE
Add way to not add wrappers when the wrappers are already in the buffer.

### PR DESCRIPTION
**Pull request by okamsn**
I'm still in the habit of typing `cape-elisp-symbol`'s wrappers manually, so I really only want the wrapping characters inserted when they're not already there.  This PR adds that.

- Add user option `cape-elisp-symbol-bare-only`, defaulting to `nil` to keep the previous behavior.

- Modify `cape--symbol-exit` to check when the new option is non-`nil`.

Do you have any opinions on the user option's name or how this is implemented?

### CODE REVIEW

**Comment by minad** [comment]
Hi! First I wonder how this is supposed to work, given that `cape-elisp-symbol` will include the wrappers as part of the symbol itself during completion. Can you please describe how you insert symbols exactly? You first insert the wrappers and then you move point between the wrappers and initiate completion? I'd prefer if we don't add an option but make the insertion more intelligent. But if it turns out that you almost never want to insert wrappers anyway, then my suggestion would be to set `cape-elisp-symbol-wrapper` to nil and we leave things as is.

**Comment by okamsn** [comment]
> Hi! 

Hello

> First I wonder how this is supposed to work, given that `cape-elisp-symbol` will include the wrappers as part of the symbol itself during completion. 

I don't see that behavior on Emacs 29 with Corfu. For me, it only shows the symbol names in the corfu pop-up, and it inserts the wrappers afterwards.  Below is an image of the completion using Corfu in Markdown Mode. The completion for symbols triggers without me needing to write the wrappers.

example_elisp_symbol_corfu

When selecting the candidate, the wrappers are then inserted, as in the following image.

example_elisp_symbol_corfu2

Do you see different behavior? Are the wrapping characters included in the Corfu pop-up for you?

> Can you please describe how you insert symbols exactly? 

I use Markdown Mode for `git-commit-major-mode`, so I wrap Emacs Lisp symbols and file names in backticks. For completing symbols via `cape-elisp-symbol`, I don't need to write the wrappers, because they are automatically inserted. For filenames, I do need to write the wrappers. Because of this, I sometimes write the wrappers when I don't need to. When this happens, the `elisp-symbol` CAPF inserts the wrappers, even when they're not needed, because the characters are already written. 

> You first insert the wrappers and then you move point between the wrappers and initiate completion? 

No, I use packages like Smartparens. I don't think about whether or not the wrappers need to be written for a particular CAPF, I just focus on the words written, which the completion helps me type.

> I'd prefer if we don't add an option but make the insertion more intelligent. 

I think that the intelligent behavior would be to not insert more wrappers when they are already in the buffer and already surround the just-inserted candidate. I'm not sure if there is a case for the wrappers to be duplicated when they are already in the buffer. I included a user option in this PR in case there was such a case, but I will remove it if that makes this PR more agreeable.

Without the change, the completion still triggers when I type symbol names as in the following image.

example3

However, when I select the candidate, the wrappers are duplicated because `cape--symbol-exit` inserts them unconditionally.

example4

> But if it turns out that you almost never want to insert wrappers anyway, then my suggestion would be to set `cape-elisp-symbol-wrapper` to nil and we leave things as is.

It is not that I never want the wrappers inserted. The automatic wrapping is useful and a good feature. It is that I think it would be better if the wrappers were not inserted when they are already in the buffer. I think conditional insertion would be more like Do What I Mean behavior.

**Comment by minad** [comment]
What I meant is that the beforehand inserted wrappers are already recognized as part of the symbol token, so it doesn't work at all if you first insert the wrappers. However this is not the case in Markdown, so there are certainly scenarios where condition wrapper insertion makes sense. In any case, the option shouldn't be needed. Also the insertion function should be simplified, since it looks way too complex right now.

**Comment by okamsn** [comment]
Thank you for making the change. I confirm that what you did works for me.

**Pull request closed without merging**
