### PR TITLE
Add Elixir keywords

### PR DESCRIPTION
**Pull request by ashton314**
This adds keywords from Elixir. I scraped these off of the `Kernel` namespace (see the [docs](https://hexdocs.pm/elixir/Kernel.html)) which gets auto-imported everywhere. This might as well be considered the builtins of the language.

### CODE REVIEW

**Comment by ashton314** [comment]
> Copyright assignment for the FSF

I've never done that before. How do I get started? (Sheesh… I thought this would be an easy contribution. 😅 It'll be worth it though!)

> PR for company-mode
Just opened here: https://github.com/company-mode/company-mode/pull/1353

Looks like I'll need the FSF copyright assignment for that too.

**Comment by minad** [comment]
See the step description here: https://protesilaos.com/emacs/modus-themes#h:111773e2-f26f-4b68-8c4f-9794ca6b9633

**Comment by ashton314** [comment]
If course Prot would have a nice write-up of how to do this. Thanks for the pointer—I'll get on this.

To be clear: is this something I have to complete on a per-project basis?

**Comment by minad** [comment]
You can do it once for all your Emacs contributions.

**Pull request merged**
